---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pollspain

<!-- badges: start -->
<!-- badges: end -->

## Overview

The goal of pollspain is to ...

## Installation

You can install the development version of R package `{pollspain}` from [GitHub](https://github.com/) through the following code:

```{r eval = FALSE}
install.packages("devtools") # only if not already installed
devtools::install_github("dadosdelaplace/pollspain")
```

```{r echo = FALSE, message = FALSE}
devtools::install_github("dadosdelaplace/pollspain")
```

```{r}
library(pollspain)
```

## Usage

### get functions

#### Census data


Variables concerning population (`pop_res_mun`, `census_INE_mun`, `census_counting_mun`, `census_CERE_mun`)

```{r}
mun_census_data <- get_mun_census_data("congress", 2019, 4)
mun_census_data
```




