name: DuckDB Test Only (Linux)

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  test-duckdb:
    runs-on: ubuntu-latest
    name: Run duckdb-specific test

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("testthat", "duckdb", "DBI", "dplyr"))
        shell: Rscript {0}

      - name: Run duckdb test file
        run: |
          testthat::test_file("tests/testthat/test-duckdb.R")
        shell: Rscript {0}
